name: deploy-suzuito-godzilla
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy-suzuito-godzilla:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: suzuito-godzilla
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-godzilla
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY_GODZILLA }}
          export_default_credentials: true
      - run: gsutil rm -r gs://${{env.GCP_PROJECT_ID}}-blog1-server/*
        continue-on-error: true
      - run: gsutil cp -r dist/blog1/* gs://${{env.GCP_PROJECT_ID}}-blog1-server
