name: minilla-deploy
on:
  push:
    branches:
      - main
    tags:
      - qa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-minilla
      # - uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --project=blog-minilla
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: blog-minilla
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gsutil rm -r gs://blog-static-minilla/app/*
      - run: gsutil cp -r dist/blog1/* gs://blog-static-minilla/app
